FROM alpine:latest

ARG BUILD_DIR="./build"

COPY "${BUILD_DIR}/relay/ws-relayd/" /
COPY "${BUILD_DIR}/relay/lobby_public.pem" /lobby_public.pem

RUN chmod +x /ws-relayd

ENV RELAY_ADDR=:4099
ENV PROMETHEUS_ADDR=:4422
#ENV ALLOW_SERVER_WITHOUT_AUTH="-allow-server-without-authentication"
ENV ALLOW_SERVER_WITHOUT_AUTH=""
ENV JWT_KEY_FILE=/lobby_public.pem

CMD /ws-relayd -addr $RELAY_ADDR -prometheus-addr $PROMETHEUS_ADDR -jwt-key-type ecdsa -jwt-key-file $JWT_KEY_FILE $ALLOW_SERVER_WITHOUT_AUTH
