lobby:
  name: jetbrains-cwm-lobby
  replicaCount: 1
  image: jetbrains/cwm/lobby
  tag: latest
  pullPolicy: Always
  keyFile: "/home/lobby-server/lobby_private.pem"
  port: 8080
  service:
    type: NodePort
    port: 443
  resources: {}
  ingress:
    name: jetbrains-cwm-lobby
    host: cwm-lobby-test.local
    path: "/"

relay:
  name: jetbrains-cwm-relay
  replicaCount: 1
  image: jetbrains/cwm/relay
  tag: latest
  pullPolicy: Always
  jwtKeyFile: "/lobby_public.pem"
  port: 8080
  service:
    type: NodePort
    port: 443
  resources: {}
  ingress:
    name: jetbrains-cwm-relay
    host: cwm-relay-test.local
    path: ""

redis:
  name: jetbrains-cwm-redis
  replicaCount: 1
  image: redis
  tag: latest
  pullPolicy: Always
  service:
    type: NodePort
    port: 6379
    targetPort: 6379
  resources: {}

