apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.lobby.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.lobby.name }}
    app.kubernetes.io/managed-by: helm
    app: {{ .Values.lobby.name }}
spec:
  replicas: {{ .Values.lobby.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.lobby.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.lobby.name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8880"
        prometheus.io/scheme: "http"
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.lobby.configMapName }}
          items:
            - key: "config.json"
              path: "config.json"
      containers:
        - name: {{ .Values.lobby.name }}
          image: "{{ .Values.lobby.image }}:{{ .Values.lobby.tag }}"
          imagePullPolicy: {{ .Values.lobby.pullPolicy }}
          ports:
            - containerPort: {{ .Values.lobby.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.lobby.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /home/lobby-server/config
          env:
            - name: SERVER_PORT
              value: "{{ .Values.lobby.port }}"
            - name: DIAGNOSTICS_PORT
              value: "8880"
            - name: FORCE_RELAY_URI
              value: "wss://{{ .Values.relay.ingress.host }}"
            - name: RELAYS_ECDSA_JWT_KEY_FILE
              value: "{{ .Values.lobby.keyFile }}"
            - name: REDIS_HOST
              value: "{{ .Values.redis.name }}"
            - name: REDIS_PORT
              value: "{{ .Values.redis.service.port }}"
            - name: ENABLED_FEATURES
              value: "direct_tcp,ws_relay"
            - name: BASE_URL
              value: "https://{{ .Values.lobby.ingress.host }}"
            - name: CONFIG_JSON
              value: "/home/lobby-server/config/config.json"
