apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  template:
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: "{{ .Values.redis.image }}:{{ .Values.redis.tag }}"
          imagePullPolicy: {{ .Values.redis.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          env:
            - name: THING
              value: REDIS
