apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.lobby.ingress.name }}
spec:
  rules:
    - host: {{ .Values.lobby.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.lobby.ingress.path | quote }}
            backend:
              serviceName: {{ .Values.lobby.name }}
              servicePort: https
