apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.relay.name }}
spec:
  type: {{ .Values.relay.service.type }}
  ports:
    - port: {{ .Values.relay.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.relay.name }}

