apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.lobby.name }}
spec:
  type: {{ .Values.lobby.service.type }}
  ports:
    - port: {{ .Values.lobby.service.port }}
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: {{ .Values.lobby.name }}
